---
title: "Assignment-Yuwei"
author: "Yuwei Ni"
date: "6/8/2018"
output: html_document
---

```{r}
#Download the package
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("rhdf5")

#check the vignette
#browseVignettes(package = "rhdf5")

setwd("/Users/summer/Downloads/package/beachball")
```



```{r}
#simulate the matrix
set.seed(123)
data<-matrix(rnorm(1000*100,mean = 0.5,sd=0.3),1000,100)
```


```{r}
#create the HDF5 file and write the matrix
library(rhdf5)
h5createFile("assignment.h5")
h5write(data,"assignment.h5","matrix1")
h5<-h5read("assignment.h5","matrix1")

#check the results are same
identical(data,h5)
```


```{r}
#download the HDF5array Package
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
#biocLite("HDF5Array")
library(HDF5Array)
library(tidyverse)

#getHDF5DumpDir()
getwd()
setHDF5DumpFile("/Users/summer/Downloads/package/beachball/assignment1")

as(data,"HDF5Array")
lsHDF5DumpFile()


#save the matrix as an HDF5-based object
library(SummarizedExperiment)
matrix2<-SummarizedExperiment(assays = data)
dir<-sub("/Users/summer/Downloads/package/beachball","hdf5matrix",tempfile())
hdf5matrix<-saveHDF5SummarizedExperiment(matrix2,dir)


h5_matrix<-loadHDF5SummarizedExperiment(dir)
h5_matrix
assay(h5_matrix)
colMeans(assay(h5_matrix))
```


```{r}
#calculate the mean of each columns

#natural method
colMeans(data)

#hdf5 method
h5_matrix<-loadHDF5SummarizedExperiment(dir)
colMeans(assay(h5_matrix))

```


```{r}
#compare the speed
system.time(colMeans(data))
system.time(colMeans(assay(h5_matrix)))
```

