# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

debug <- function(data, CENTROIDS = NULL) {
    .Call(`_beachball_debug`, data, CENTROIDS)
}

transfer_data <- function(data) {
    .Call(`_beachball_transfer_data`, data)
}

#'
#' Mini_batch
#'
#' Mini-batch-k-means for both matrix and HDF5Matrix
#'
#'@param data numeric matrix or integer matrix or HDF5Matrix
#'@param clusters the number of clusters
#'@param batch_size the size of the mini batches
#'@param num_init number of times the algorithm will be run with different centroid seeds
#'@param max_iters the maximum number of clustering iterations
#'@param init_fraction percentage of data to use for the initialization centroids (applies if initializer is \emph{kmeans++} ). Should be a float number between 0.0 and 1.0.
#'@param initializer the method of initialization. One of \emph{kmeans++} and \emph{random}. See details for more information
#'@param early_stop_iter continue that many iterations after calculation of the best within-cluster-sum-of-squared-error
#'@param verbose either TRUE or FALSE, indicating whether progress is printed during clustering
#'@param CENTROIDS a matrix of initial cluster centroids. The rows of the CENTROIDS matrix should be equal to the number of clusters and the columns should be equal to the columns of the data
#'@param tol a float number. If, in case of an iteration (iteration > 1 and iteration < max_iters) 'tol' is greater than the squared norm of the centroids, then kmeans has converged
#'@param seed integer value for random number generator (RNG)
#'@return a list with the following attributes: centroids, WCSS_per_cluster, best_initialization, iters_per_initialization
#'@details
#'This function performs k-means clustering using mini batches.
#'
#'\strong{kmeans++}: kmeans++ initialization. Reference : http://theory.stanford.edu/~sergei/papers/kMeansPP-soda.pdf AND http://stackoverflow.com/questions/5466323/how-exactly-does-k-means-work
#'
#'\strong{random}: random selection of data rows as initial centroids
#'
#'@references
#'https://github.com/mlampros/ClusterR
#'
#'@examples
#'data = matrix(1:30,nrow = 10)
#'data1 = as(data,"HDF5Matrix)
#'
#' @export
mini_batch <- function(data, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, seed = 1L) {
    .Call(`_beachball_mini_batch`, data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, seed)
}

predict_mini_batch <- function(data, CENTROIDS = NULL, fuzzy = FALSE, eps = 1.0e-6) {
    .Call(`_beachball_predict_mini_batch`, data, CENTROIDS, fuzzy, eps)
}

set_seed <- function(seed) {
    invisible(.Call(`_beachball_set_seed`, seed))
}

cluster_indices <- function(CLUSTER) {
    .Call(`_beachball_cluster_indices`, CLUSTER)
}

check_NaN_Inf <- function(x) {
    .Call(`_beachball_check_NaN_Inf`, x)
}

calc_silhouette <- function(intra, outer) {
    .Call(`_beachball_calc_silhouette`, intra, outer)
}

sample_vec <- function(num_elem, start, end, replace) {
    .Call(`_beachball_sample_vec`, num_elem, start, end, replace)
}

squared_norm <- function(x) {
    .Call(`_beachball_squared_norm`, x)
}

MinMat <- function(x) {
    .Call(`_beachball_MinMat`, x)
}

WCSS <- function(vec, centroids) {
    .Call(`_beachball_WCSS`, vec, centroids)
}

validate_centroids <- function(data, init_centroids) {
    .Call(`_beachball_validate_centroids`, data, init_centroids)
}

kmeans_pp_dist <- function(vec, centroid) {
    .Call(`_beachball_kmeans_pp_dist`, vec, centroid)
}

kmeans_pp_init <- function(data, clusters, medoids = FALSE) {
    .Call(`_beachball_kmeans_pp_init`, data, clusters, medoids)
}

norm_fuzzy <- function(vec, eps) {
    .Call(`_beachball_norm_fuzzy`, vec, eps)
}

quantile_value <- function(x, clusters) {
    .Call(`_beachball_quantile_value`, x, clusters)
}

duplicated_flag <- function(x) {
    .Call(`_beachball_duplicated_flag`, x)
}

quantile_init_rcpp <- function(data, sample_rows, clusters) {
    .Call(`_beachball_quantile_init_rcpp`, data, sample_rows, clusters)
}

check_medoids <- function(data, clust, tol = 0.5) {
    .Call(`_beachball_check_medoids`, data, clust, tol)
}

SCALE <- function(data, mean_center = TRUE, sd_scale = TRUE) {
    .Call(`_beachball_SCALE`, data, mean_center, sd_scale)
}

