# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call('_beachball_set_seed', PACKAGE = 'beachball', seed))
}

cluster_indices <- function(CLUSTER) {
    .Call('_beachball_cluster_indices', PACKAGE = 'beachball', CLUSTER)
}

check_NaN_Inf <- function(x) {
    .Call('_beachball_check_NaN_Inf', PACKAGE = 'beachball', x)
}

calc_silhouette <- function(intra, outer) {
    .Call('_beachball_calc_silhouette', PACKAGE = 'beachball', intra, outer)
}

sample_vec <- function(num_elem, start, end, replace) {
    .Call('_beachball_sample_vec', PACKAGE = 'beachball', num_elem, start, end, replace)
}

squared_norm <- function(x) {
    .Call('_beachball_squared_norm', PACKAGE = 'beachball', x)
}

MinMat <- function(x) {
    .Call('_beachball_MinMat', PACKAGE = 'beachball', x)
}

WCSS <- function(vec, centroids) {
    .Call('_beachball_WCSS', PACKAGE = 'beachball', vec, centroids)
}

validate_centroids <- function(data, init_centroids) {
    .Call('_beachball_validate_centroids', PACKAGE = 'beachball', data, init_centroids)
}

kmeans_pp_dist <- function(vec, centroid) {
    .Call('_beachball_kmeans_pp_dist', PACKAGE = 'beachball', vec, centroid)
}

kmeans_pp_init <- function(data, clusters, medoids = FALSE) {
    .Call('_beachball_kmeans_pp_init', PACKAGE = 'beachball', data, clusters, medoids)
}

norm_fuzzy <- function(vec, eps) {
    .Call('_beachball_norm_fuzzy', PACKAGE = 'beachball', vec, eps)
}

quantile_value <- function(x, clusters) {
    .Call('_beachball_quantile_value', PACKAGE = 'beachball', x, clusters)
}

duplicated_flag <- function(x) {
    .Call('_beachball_duplicated_flag', PACKAGE = 'beachball', x)
}

quantile_init_rcpp <- function(data, sample_rows, clusters) {
    .Call('_beachball_quantile_init_rcpp', PACKAGE = 'beachball', data, sample_rows, clusters)
}

check_medoids <- function(data, clust, tol = 0.5) {
    .Call('_beachball_check_medoids', PACKAGE = 'beachball', data, clust, tol)
}

SCALE <- function(data, mean_center = TRUE, sd_scale = TRUE) {
    .Call('_beachball_SCALE', PACKAGE = 'beachball', data, mean_center, sd_scale)
}

mini_batch_kmeans <- function(data, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, tol_optimal_init = 0.5, seed = 1L) {
    .Call('_beachball_mini_batch_kmeans', PACKAGE = 'beachball', data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed)
}

