# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute column sums from matrix using beachmat
#'
#' Input is a numeric matrix of any of the types supported by beachmat.
#'
#' @param dmat a matrix.
#'
#' @return A vector with column means.
#' @export
beachmat_colSums <- function(dmat) {
    .Call(`_beachball_beachmat_colSums`, dmat)
}

#' @export
debug <- function(data, CENTROIDS = NULL, fuzzy = FALSE, eps = 1.0e-6) {
    .Call(`_beachball_debug`, data, CENTROIDS, fuzzy, eps)
}

#' @export
mini_batch <- function(data, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, tol_optimal_init = 0.5, seed = 1L) {
    .Call(`_beachball_mini_batch`, data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed)
}

predict_mini_batch <- function(data, CENTROIDS = NULL, fuzzy = FALSE, eps = 1.0e-6) {
    .Call(`_beachball_predict_mini_batch`, data, CENTROIDS, fuzzy, eps)
}

random_choose <- function(data, init_fraction) {
    .Call(`_beachball_random_choose`, data, init_fraction)
}

#' @export
mini_batch_kmeans <- function(data, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, tol_optimal_init = 0.5, seed = 1L) {
    .Call(`_beachball_mini_batch_kmeans`, data, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed)
}

make_to_string <- function(str) {
    .Call(`_beachball_make_to_string`, str)
}

get_class <- function(incoming) {
    .Call(`_beachball_get_class`, incoming)
}

get_safe_slot <- function(incoming, slotname) {
    .Call(`_beachball_get_safe_slot`, incoming, slotname)
}

transfer_data <- function(data) {
    .Call(`_beachball_transfer_data`, data)
}

#' @export
Week4_mini_batch_kmeans <- function(dat, clusters, batch_size, max_iters, num_init = 1L, init_fraction = 1.0, initializer = "kmeans++", early_stop_iter = 10L, verbose = FALSE, CENTROIDS = NULL, tol = 1e-4, tol_optimal_init = 0.5, seed = 1L) {
    .Call(`_beachball_Week4_mini_batch_kmeans`, dat, clusters, batch_size, max_iters, num_init, init_fraction, initializer, early_stop_iter, verbose, CENTROIDS, tol, tol_optimal_init, seed)
}

#' @export
matrix_mean <- function(data) {
    .Call(`_beachball_matrix_mean`, data)
}

